version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   # warm nix
   - run: nix-shell -vvv --run echo
   # run tests
   - run: nix-shell -vvv --run hn-test

 mac:
  macos:
   xcode: "10.2.0"
  steps:
   - checkout
   - run:
      name: Warm nix
      command: |
       curl https://nixos.org/nix/install | sh
       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
       nix-shell -vvv --run echo
  # run tests
   - run: nix-shell -vvv --run hn-test

workflows:
 version: 2
 tests:
  jobs:
   - build
   - mac
