version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout

   # warm nix
   - run: nix-shell --run echo

   # run env tests
   - run: ./test/nix-env.sh

   # run shell tests
   - run: nix-shell --run hn-test

 debian:
  docker:
   - image: debian:buster
  steps:
   - checkout

   - run: docker build ./Dockerfile.debian

 mac:
  macos:
   xcode: "10.2.0"
  steps:
   - checkout
   - run:
      name: Warm nix
      command: |
       curl https://nixos.org/nix/install | sh
       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
       # same as linux from here
       nix-shell --run echo
       ./test/nix-env.sh
       nix-shell --run hn-test

workflows:
 version: 2
 tests:
  jobs:
   - build
   - debian
   - mac
