version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   # warm nix
   - run: nix-shell --run echo
   # run tests
   - run: nix-shell --run hn-test

 mac:
  macos:
   xcode: "10.2.0"
  steps:
   - checkout
   - run:
      name: Warm nix
      command: |
       curl https://nixos.org/nix/install | sh
       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
       nix-shell --run hn-test
   - run: nix-shell https://holochain.love | sh
       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
       hc init my_first_app
       cd my_first_app
       hc generate zomes/my_zome
       hc test


workflows:
 version: 2
 tests:
  jobs:
   - build
   - mac
