version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout

   # warm nix
   - run: nix-shell --run echo

   # run env tests
   - run: ./test/nix-env.sh

   # run shell tests
   - run: nix-shell --run hn-test

 debian:
  docker:
   - image: holochain/holonix:debian
  steps:
   - checkout

   - run:
      command: |
       . /home/docker/.nix-profile/etc/profile.d/nix.sh
       nix-shell --run echo
       ./test/nix-env.sh
       nix-shell --run hn-test

 ubuntu:
  docker:
   - image: holochain/holonix:ubuntu
  steps:
   - checkout

   - run:
      command: |
       . /home/docker/.nix-profile/etc/profile.d/nix.sh
       nix-shell --run echo
       ./test/nix-env.sh
       nix-shell --run hn-test

 # THIS IS SECURITY SENSITVE
 # READ THESE
 # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
 # https://discuss.circleci.com/t/adding-ssh-keys-fails/7747/24
 deploy-github-pages:
  docker:
   - image: holochain/holonix:latest
  steps:
   - add_ssh_keys:
      fingerprints:
       - "52:70:20:1e:fe:e3:1c:74:cc:b9:5e:b4:04:30:03:e6"
   - checkout
   - run:
      name: Deploy github pages
      command: |
       git config user.name "$GITHUB_PAGES_DEPLOY_USER"
       git config user.email "$GITHUB_PAGES_DEPLOY_EMAIL"
       nix-shell --run hn-docs-github-pages

 mac:
  macos:
   xcode: "10.2.0"
  steps:
   - checkout
   - run:
      name: Standard tests
      command: |
       curl https://nixos.org/nix/install | sh
       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
       nix-shell --run echo
       ./test/nix-env.sh
       nix-shell --run hn-test

 docker.build.holonix:
  machine: true
  steps:
   - checkout
   - setup_remote_docker
   - run: docker build ./docker -f ./docker/Dockerfile.nix --no-cache

workflows:
 version: 2
 tests:
  jobs:
   - build
   - debian
   - ubuntu
   - mac
   - docker.build.holonix
   - deploy-github-pages:
      filters:
       branches:
        only: master
      requires:
       - build
